//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS_11_Coursova.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Load
    {
        public int LoadID { get; set; }
        public int TeacherID { get; set; }
        public int DisciplineID { get; set; }
        public int TypeLoadID { get; set; }
        public int Hours { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual TypeLoad TypeLoad { get; set; }
    }
}
